server:
  port: 8086

jdbc:
  url: jdbc:postgresql://84.201.167.2:5432/simple_db
  username: db_user
  password: qwerty

liquibase:
  change-log: classpath:liquibase/db.changelog.xml

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  autoStartup: false