server:
  port: 7072

jdbc:
  url: jdbc:postgresql://84.201.167.2:5432/simple_db
  username: db_user
  password: qwerty

liquibase:
    change-log: classpath:liquibase/db.changelog.xml

spring:
  kafka:
    bootstrap-servers: http://130.193.55.12:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer